export const DummyUserList = {
  users: {
    docs: [
      {
        _id: "1",
        username: "hello",
        email: "hello@mailinator.com",
        isEmailVerified: false,
        userType: 2,
        firstName: "Hello",
        lastName: "World",
        gender: "FEMALE",
        age: 20,
        heightUnit: "CM",
        height: 200,
        weightUnit: "KG",
        weight: 90,
        birthYear: 1998,
        skinType: "COMBINED",
        skinTone: null,
        createdAt: "2024-01-10T14:13:33.468Z",
        updatedAt: "2024-01-19T11:04:27.918Z",
        __v: 0,
        status: 1,
      },
      {
        _id: "2",
        username: "string",
        email: "string@mailinator.com",
        isEmailVerified: false,
        userType: 2,
        firstName: null,
        lastName: null,
        gender: "MALE",
        age: 25,
        heightUnit: "CM",
        height: 150,
        weightUnit: "KG",
        weight: 70,
        birthYear: 1990,
        skinType: "COMBINED",
        skinTone: null,
        createdAt: "2024-01-09T17:50:57.929Z",
        updatedAt: "2024-01-22T13:17:24.704Z",
        __v: 0,
        status: 1,
      },
    ],
    meta: {
      totalDocs: 9,
      totalPages: 5,
      page: 1,
    },
  },
};
